config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.login.views import LoginFormView

urlpatterns = [
    path('', LoginFormView.as_view()),
    path('formatos/', include('core.formatos.urls')),
    path('login/', include('core.login.urls')),
    path('admin/', admin.site.urls),
]

core/formatos/urls.py
from django.urls import path
from django.conf.urls import url
from core.formatos.views import FormulariosIndex, Format_Sintomas, Crear_Nuevo_Formato, Lista_Formatos_Sintomas

app_name = 'formatos'

urlpatterns = [
    path('', FormulariosIndex, name='IndexFormatos'),
    path('sintomas/', Format_Sintomas, name='Crear_Formato_Sintomas'),
    path('sintomas/lista', Lista_Formatos_Sintomas, name='Lista_Formatos_Generados'),
    url(r'^sintomas/guardar/$', Crear_Nuevo_Formato, name='Guardar_Formato_Sintomas'),
]

templates/LayoutPrincipal.html
{% load static %}
{% if user.is_authenticated %}
<!doctype html>
<html class="no-js" lang="es">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Incio - NC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" type="image/png" href="{% static 'assets/images/icon/favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/metisMenu.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/slicknav.min.css' %}">
  <!-- amchart css -->
  <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css'" type="text/css" media="all" />
  <!-- others css -->
  <link rel="stylesheet" href="{% static 'assets/css/typography.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/default-css.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
  <!-- modernizr css -->
  <script src="{% static 'assets/js/vendor/modernizr-2.8.3.min.js' %}"></script>
  <!-- checkbox Personalizados -->
  <link rel="stylesheet" href="{% static 'dist/checkbox.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/personalizando.css' %}">
</head>

<body>
  <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
  <!-- preloader area start -->
  <div id="preloader">
    <div class="loader"></div>
  </div>
  <!-- preloader area end -->
  <!-- page container area start -->
  <div class="page-container">
    <!-- sidebar menu area start -->
    <div class="sidebar-menu">
      <div class="sidebar-header">
        <div class="logo">
          <a href="#"><img src="{% static 'assets/images/icon/logo.png' %}" alt="logo"></a>
        </div>
      </div>
      <div class="main-menu">
        <div class="menu-inner">
          <nav>
            <ul class="metismenu" id="menu">
              <li class="active">
                <a href="javascript:void(0)" aria-expanded="true"><i class="ti-dashboard"></i><span>Dashboard</span></a>
                <ul class="collapse">
                  <li class="active"><a href="{% url 'formatos:IndexFormatos'%}">Formatos</a></li>
                  <!--<a href="#">F</a></li>
                  <li><a href="#">Menuitem 3</a></li>
                </ul>
              </li>
              <li><a href="#"><i class="ti-map-alt"></i><span>Not expanding</span></a></li>
              <li>
                <a href="javascript:void(0)" aria-expanded="true"><i class="fa fa-align-left"></i>
                  <span>Multi
                    level menu</span></a>
                <ul class="collapse">
                  <li><a href="#">Item level (1)</a></li>
                  <li><a href="#">Item level (1)</a></li>
                  <li><a href="#" aria-expanded="true">Item level (1)</a>
                    <ul class="collapse">
                      <li><a href="#">Item level (2)</a></li>
                      <li><a href="#">Item level (2)</a></li>
                      <li><a href="#">Item level (2)</a></li>
                    </ul>
                  </li>
                  <li><a href="#">Item level (1)</a></li>-->
                </ul>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <!-- sidebar menu area end -->
    <!-- main content area start -->
    <div class="main-content">
      <!-- header area start -->
      <div class="header-area">
        <div class="row align-items-center">
          <!-- nav and search button -->
          <div class="col-md-6 col-sm-8 clearfix">
            <div class="nav-btn pull-left">
              <span></span>
              <span></span>
              <span></span>
            </div>
            <div class="search-box pull-left">
              <form action="#">
                <input type="text" name="search" placeholder="Search..." required>
                <i class="ti-search"></i>
              </form>
            </div>
          </div>
          <!-- profile info & task notification -->
          <div class="col-md-6 col-sm-4 ">
            <div class="user-profile pull-right clearfix">
              <img class="avatar user-thumb" src="{{request.user.obtener_imagen }}" alt="avatar">
              <h4 class="user-name dropdown-toggle" data-toggle="dropdown"> {{ request.user.first_name  }} {{request.user.last_name}} <i class="fa fa-angle-down"></i></h4>
              <div class="dropdown-menu">
                <!--<a class="dropdown-item" href="#">Message</a>
                <a class="dropdown-item" href="#">Settings</a>-->
                <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesion</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- header area end -->
      <!-- page title area start -->
      <div class="page-title-area">
        <div class="row align-items-center">
          <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix p-1">
              <h4 class="page-title pull-left">Dashboard</h4>
              <ul class="breadcrumbs pull-left">
                <li><a href="index.html">Home</a></li>
                <li><span>Dashboard</span></li>
              </ul>
            </div>
          </div>
          <div class="col-sm-6 clearfix">

          </div>
        </div>
      </div>
      <!-- page title area end -->
      <div class="main-content-inner">
        <!-- MAIN CONTENT GOES HERE -->
        {% block content  %}
        {% endblock %}
      </div>
    </div>
    <!-- main content area end -->
    <!-- footer area start-->
    <footer>
      <div class="footer-area">
        <p>© Copyright 2018. All right reserved. Template by <a href="https://colorlib.com/wp/">Colorlib</a>.</p>
      </div>
    </footer>
    <!-- footer area end-->
  </div>
  <!-- page container area end -->
  <!-- offset area start -->
  <div class="offset-area">
    <div class="offset-close"><i class="ti-close"></i></div>
    <ul class="nav offset-menu-tab">
      <li><a class="active" data-toggle="tab" href="#activity">Activity</a></li>
      <li><a data-toggle="tab" href="#settings">Settings</a></li>
    </ul>
    <div class="offset-content tab-content">
      <div id="activity" class="tab-pane fade in show active">
        <div class="recent-activity">
          <div class="timeline-task">
            <div class="icon bg1">
              <i class="fa fa-envelope"></i>
            </div>
            <div class="tm-title">
              <h4>Rashed sent you an email</h4>
              <span class="time"><i class="ti-time"></i>09:35</span>
            </div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse distinctio itaque at.
            </p>
          </div>
          <div class="timeline-task">
            <div class="icon bg2">
              <i class="fa fa-check"></i>
            </div>
            <div class="tm-title">
              <h4>Added</h4>
              <span class="time"><i class="ti-time"></i>7 Minutes Ago</span>
            </div>
            <p>Lorem ipsum dolor sit amet consectetur.
            </p>
          </div>
          <div class="timeline-task">
            <div class="icon bg2">
              <i class="fa fa-exclamation-triangle"></i>
            </div>
            <div class="tm-title">
              <h4>You missed you Password!</h4>
              <span class="time"><i class="ti-time"></i>09:20 Am</span>
            </div>
          </div>
          <div class="timeline-task">
            <div class="icon bg3">
              <i class="fa fa-bomb"></i>
            </div>
            <div class="tm-title">
              <h4>Member waiting for you Attention</h4>
              <span class="time"><i class="ti-time"></i>09:35</span>
            </div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse distinctio itaque at.
            </p>
          </div>
        </div>
      </div>
      <div id="settings" class="tab-pane fade">
        <div class="offset-settings">
          <h4>General Settings</h4>
          <div class="settings-list">
            <div class="s-settings">
              <div class="s-sw-title">
                <h5>Notifications</h5>
                <div class="s-swtich">
                  <input type="checkbox" id="switch1" />
                  <label for="switch1">Toggle</label>
                </div>
              </div>
              <p>Keep it 'On' When you want to get all the notification.</p>
            </div>
            <div class="s-settings">
              <div class="s-sw-title">
                <h5>Show recent activity</h5>
                <div class="s-swtich">
                  <input type="checkbox" id="switch2" />
                  <label for="switch2">Toggle</label>
                </div>
              </div>
              <p>The for attribute is necessary to bind our custom checkbox with the input.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- offset area end -->
  <!-- jquery latest version -->
  <script src="{% static 'assets/js/vendor/jquery-2.2.4.min.js' %}"></script>
  <!-- bootstrap 4 js -->
  <script src="{% static 'assets/js/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/metisMenu.min.js' %}"></script>
  <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.slimscroll.min.js' %}"></script>
  <script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

  <!-- start chart js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
  <!-- start highcharts js -->
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <!-- start zingchart js -->
  <script src="https://cdn.zingchart.com/zingchart.min.js"></script>
  <script>
    zingchart.MODULESDIR = "https://cdn.zingchart.com/modules/";
    ZC.LICENSE = ["569d52cefae586f634c54f86dc99e6a9", "ee6b7db5b51705a13dc2339db3edaf6d"];
  </script>
  <!-- all line chart activation -->
  <script src="{% static 'assets/js/line-chart.js' %}"></script>
  <!-- all pie chart -->
  <script src="{% static 'assets/js/pie-chart.js' %}"></script>
  <!-- others plugins -->
  <script src="{% static 'assets/js/plugins.js' %}"></script>
  <script src="{% static 'assets/js/scripts.js' %}"></script>
  {% block javascript %}
  {% endblock %}
</body>

</html>
{% else %}
{% include 'login.html' %}
{% endif %}